-- MySQL Script generated by MySQL Workbench
-- Tue Dec 16 11:35:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema weighsoft
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `weighsoft` ;

-- -----------------------------------------------------
-- Schema weighsoft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weighsoft` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `weighsoft` ;

-- -----------------------------------------------------
-- Table `axelsetups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `axelsetups` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `axelsetups` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `steering` VARCHAR(255) NOT NULL DEFAULT '',
  `steering_max` INT(11) NOT NULL DEFAULT 0,
  `axel_1` VARCHAR(255) NOT NULL DEFAULT '',
  `axel_1_max` INT(11) NOT NULL DEFAULT 0,
  `axel_2` VARCHAR(255) NOT NULL DEFAULT '',
  `axel_2_max` INT(11) NOT NULL DEFAULT 0,
  `axel_3` VARCHAR(255) NOT NULL DEFAULT '',
  `axel_3_max` INT(11) NOT NULL DEFAULT 0,
  `axel_4` VARCHAR(255) NOT NULL DEFAULT '',
  `axel_4_max` INT(11) NOT NULL DEFAULT 0,
  `vehicle_max` INT(11) NOT NULL DEFAULT 0,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `axelsetups_company_id_foreign` ON `axelsetups` (`company_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `axelsetups_tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `axelsetups_tracking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `axelsetups_tracking` (
  `id` INT(11) NOT NULL,
  `update_scope_id` VARCHAR(36) NULL DEFAULT NULL,
  `timestamp` BIGINT(20) NULL DEFAULT NULL,
  `sync_row_is_tombstone` BIT(1) NOT NULL DEFAULT b'0',
  `last_change_datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `axletypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `axletypes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `axletypes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Single_Steering` INT(11) NOT NULL DEFAULT 0,
  `Double_Steering` INT(11) NOT NULL DEFAULT 0,
  `Triple_Steering` INT(11) NOT NULL DEFAULT 0,
  `Single_Non_Steering` INT(11) NOT NULL DEFAULT 0,
  `Double_Non_Steering` INT(11) NOT NULL DEFAULT 0,
  `Triple_Non_Steering` INT(11) NOT NULL DEFAULT 0,
  `Double_Single_Non_Steering` INT(11) NOT NULL,
  `Double_Double_Non_Steering` INT(11) NOT NULL,
  `Double_Triple_Non_Steering` INT(11) NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `Custom_1` INT(11) NOT NULL DEFAULT 0,
  `Custom_2` INT(11) NOT NULL DEFAULT 0,
  `Custom_3` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `axletypes_company_id_foreign` ON `axletypes` (`company_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `axletypes_tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `axletypes_tracking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `axletypes_tracking` (
  `id` INT(11) NOT NULL,
  `update_scope_id` VARCHAR(36) NULL DEFAULT NULL,
  `timestamp` BIGINT(20) NULL DEFAULT NULL,
  `sync_row_is_tombstone` BIT(1) NOT NULL DEFAULT b'0',
  `last_change_datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `businesspartners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `businesspartners` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `businesspartners` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `site_id` INT(10) NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `vat_nr` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `suburb` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `postal_code` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 922
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `businesspartners_tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `businesspartners_tracking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `businesspartners_tracking` (
  `id` INT(11) NOT NULL,
  `update_scope_id` VARCHAR(36) NULL DEFAULT NULL,
  `timestamp` BIGINT(20) NULL DEFAULT NULL,
  `sync_row_is_tombstone` BIT(1) NOT NULL DEFAULT b'0',
  `last_change_datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cameras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cameras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cameras` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `pn_recog` VARCHAR(255) NOT NULL,
  `ip_address` VARCHAR(255) NOT NULL,
  `camera_active` VARCHAR(255) NOT NULL,
  `weighbridge_id` INT(10) UNSIGNED NOT NULL,
  `workstation_id` INT(10) UNSIGNED NOT NULL,
  `site_id` INT(10) UNSIGNED NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cameras_tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cameras_tracking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cameras_tracking` (
  `id` INT(11) NOT NULL,
  `update_scope_id` VARCHAR(36) NULL DEFAULT NULL,
  `timestamp` BIGINT(20) NULL DEFAULT NULL,
  `sync_row_is_tombstone` BIT(1) NOT NULL DEFAULT b'0',
  `last_change_datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `companies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `companies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `registered_name` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(255) NOT NULL,
  `fax` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `registration_number` VARCHAR(255) NOT NULL,
  `vat_nr` VARCHAR(255) NOT NULL,
  `contact_person` VARCHAR(255) NOT NULL,
  `cell` VARCHAR(255) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `suburb1` VARCHAR(255) NOT NULL,
  `city1` VARCHAR(255) NOT NULL,
  `postal_code1` VARCHAR(255) NOT NULL,
  `po_box` VARCHAR(255) NOT NULL,
  `suburb2` VARCHAR(255) NOT NULL,
  `city2` VARCHAR(255) NOT NULL,
  `postal_code2` VARCHAR(255) NOT NULL,
  `delete_transaction_flag` VARCHAR(255) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `terms` VARCHAR(4000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `companies_tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `companies_tracking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `companies_tracking` (
  `id` INT(11) NOT NULL,
  `update_scope_id` VARCHAR(36) NULL DEFAULT NULL,
  `timestamp` BIGINT(20) NULL DEFAULT NULL,
  `sync_row_is_tombstone` BIT(1) NOT NULL DEFAULT b'0',
  `last_change_datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `contract_transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contract_transactions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `contract_transactions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contract_id` INT(11) NOT NULL,
  `amount` DOUBLE(11,2) NOT NULL,
  `weighing_header_id` BINARY(16) NULL DEFAULT NULL,
  `site_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contracts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `contracts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `businesspartner_id` INT(11) NOT NULL,
  `expiry_date` DATETIME NOT NULL,
  `direction` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,4) NULL DEFAULT NULL,
  `amount` VARCHAR(255) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `company_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `reason` VARCHAR(255) NULL DEFAULT NULL,
  `linked_contact_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 146
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `errorlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `errorlog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `errorlog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `jsondata` VARCHAR(2000) NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `weighbridge_id` INT(11) NOT NULL,
  `workstation_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `company_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `exceptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exceptions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `exceptions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `jsondata` VARCHAR(2000) NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `weighbridge_id` INT(11) NOT NULL,
  `workstation_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `company_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 160
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `grades` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `grades_company_id_foreign` ON `grades` (`company_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hauliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hauliers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hauliers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `site_id` INT(10) NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `site_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 333
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `migrations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `migrations` (
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pallets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pallets` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pallets` (
  `pallet_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pallet_name` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  `company_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`pallet_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `vat` DECIMAL(11,2) NULL DEFAULT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `purchase_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `sale_price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 225
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `reporting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reporting` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `reporting` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `jsondata` VARCHAR(4000) NULL DEFAULT NULL,
  `company_id` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` VARCHAR(255) NULL DEFAULT NULL,
  `deleted_at` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `schedule` VARCHAR(20) NULL DEFAULT NULL,
  `last_report_on` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rfid_vehicles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rfid_vehicles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rfid_vehicles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `registration_number` VARCHAR(255) NOT NULL,
  `rfid` VARCHAR(255) NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `scope_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scope_info` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `scope_info` (
  `sync_scope_name` VARCHAR(100) NOT NULL,
  `sync_scope_schema` LONGTEXT NULL DEFAULT NULL,
  `sync_scope_setup` LONGTEXT NULL DEFAULT NULL,
  `sync_scope_version` VARCHAR(10) NULL DEFAULT NULL,
  `sync_scope_last_clean_timestamp` BIGINT(20) NULL DEFAULT NULL,
  `sync_scope_properties` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`sync_scope_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `scope_info_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scope_info_client` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `scope_info_client` (
  `sync_scope_id` VARCHAR(36) NOT NULL,
  `sync_scope_name` VARCHAR(100) NOT NULL,
  `sync_scope_hash` VARCHAR(100) NOT NULL,
  `sync_scope_parameters` LONGTEXT NULL DEFAULT NULL,
  `scope_last_sync_timestamp` BIGINT(20) NULL DEFAULT NULL,
  `scope_last_server_sync_timestamp` BIGINT(20) NULL DEFAULT NULL,
  `scope_last_sync_duration` BIGINT(20) NULL DEFAULT NULL,
  `scope_last_sync` DATETIME NULL DEFAULT NULL,
  `sync_scope_errors` LONGTEXT NULL DEFAULT NULL,
  `sync_scope_properties` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`sync_scope_id`, `sync_scope_name`, `sync_scope_hash`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `settings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `settings` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT 'false',
  `haulier` VARCHAR(255) NOT NULL DEFAULT 'false',
  `stored_tares` VARCHAR(255) NOT NULL DEFAULT 'false',
  `numberplate_1` VARCHAR(255) NULL DEFAULT NULL,
  `numberplate_recognition` VARCHAR(255) NOT NULL DEFAULT 'false',
  `numberplate_2` VARCHAR(255) NULL DEFAULT NULL,
  `numberplate_3` VARCHAR(255) NULL DEFAULT NULL,
  `business_partner` VARCHAR(255) NOT NULL DEFAULT 'false',
  `use_product_list` VARCHAR(255) NULL DEFAULT NULL,
  `type_of_weighing` VARCHAR(255) NOT NULL DEFAULT '0.00',
  `first_can_axel` VARCHAR(255) NOT NULL DEFAULT 'false',
  `second_can_axel` VARCHAR(255) NOT NULL DEFAULT '0.00',
  `goods_type` VARCHAR(255) NOT NULL DEFAULT 'false',
  `print_ticket` VARCHAR(255) NOT NULL DEFAULT '',
  `reprint` VARCHAR(255) NOT NULL DEFAULT 'text',
  `custom_fields` VARCHAR(255) NOT NULL,
  `user_defined_input1` TEXT NOT NULL,
  `user_defined_name1` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val1` BLOB NULL DEFAULT NULL,
  `user_defined_rep1` VARCHAR(255) NOT NULL,
  `user_defined_input2` VARCHAR(255) NULL DEFAULT 'false',
  `user_defined_name2` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val2` BLOB NOT NULL,
  `user_defined_rep2` VARCHAR(255) NOT NULL,
  `user_defined_input3` VARCHAR(255) NULL DEFAULT 'false',
  `user_defined_name3` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val3` BLOB NOT NULL,
  `user_defined_rep3` VARCHAR(255) NOT NULL,
  `user_defined_input4` VARCHAR(255) NULL DEFAULT 'false',
  `user_defined_name4` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val4` BLOB NOT NULL,
  `user_defined_rep4` VARCHAR(255) NOT NULL,
  `user_defined_input5` VARCHAR(255) NULL DEFAULT 'false',
  `user_defined_name5` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val5` BLOB NOT NULL,
  `user_defined_rep5` VARCHAR(255) NOT NULL,
  `user_defined_input6` VARCHAR(255) NULL DEFAULT 'false',
  `user_defined_name6` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val6` BLOB NOT NULL,
  `user_defined_rep6` VARCHAR(255) NOT NULL,
  `user_defined_input7` VARCHAR(255) NULL DEFAULT 'false',
  `user_defined_name7` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val7` BLOB NOT NULL,
  `user_defined_rep7` VARCHAR(255) NOT NULL,
  `user_defined_input8` VARCHAR(255) NULL DEFAULT 'false',
  `user_defined_name8` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val8` BLOB NOT NULL,
  `user_defined_rep8` VARCHAR(255) NOT NULL,
  `user_defined_input9` VARCHAR(255) NULL DEFAULT 'false',
  `user_defined_name9` VARCHAR(255) NULL DEFAULT '',
  `user_defined_val9` BLOB NOT NULL,
  `user_defined_rep9` VARCHAR(255) NOT NULL,
  `user_defined_input10` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name10` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val10` BLOB NOT NULL,
  `user_defined_rep10` VARCHAR(255) NOT NULL,
  `AS_400_path` TEXT NOT NULL,
  `export_AS400` VARCHAR(255) NOT NULL,
  `silo_verification` VARCHAR(255) NOT NULL,
  `use_cameras` VARCHAR(255) NOT NULL,
  `display_cameras` VARCHAR(255) NOT NULL,
  `print_cameras_on_ticket` VARCHAR(255) NOT NULL,
  `ticket_header` VARCHAR(255) NOT NULL,
  `display_custom_header_img` BLOB NULL DEFAULT NULL,
  `ticket_footer` BLOB NOT NULL,
  `display_custom_footer_img` BLOB NULL DEFAULT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `user_defined_input11` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name11` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val11` BLOB NULL DEFAULT NULL,
  `user_defined_rep11` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input12` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name12` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val12` BLOB NULL DEFAULT NULL,
  `user_defined_rep12` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input13` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name13` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val13` BLOB NULL DEFAULT NULL,
  `user_defined_rep13` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input14` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name14` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val14` BLOB NULL DEFAULT NULL,
  `user_defined_rep14` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input15` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name15` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val15` BLOB NULL DEFAULT NULL,
  `user_defined_rep15` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input16` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name16` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val16` BLOB NULL DEFAULT NULL,
  `user_defined_rep16` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input17` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name17` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val17` BLOB NULL DEFAULT NULL,
  `user_defined_rep17` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input18` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name18` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val18` BLOB NULL DEFAULT NULL,
  `user_defined_rep18` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input19` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name19` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val19` BLOB NULL DEFAULT NULL,
  `user_defined_rep19` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_input20` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_name20` VARCHAR(255) NULL DEFAULT NULL,
  `user_defined_val20` BLOB NULL DEFAULT NULL,
  `user_defined_rep20` VARCHAR(255) NULL DEFAULT NULL,
  `2nd_weighing` VARCHAR(255) NOT NULL,
  `invoice_enabled` VARCHAR(25) NULL DEFAULT 'false',
  `contract_enabled` VARCHAR(25) NULL DEFAULT 'false',
  `moisture_deduction_level` DECIMAL(8,2) NULL DEFAULT 0.00,
  `prefix` VARCHAR(10) NULL DEFAULT NULL,
  `enable_moisture` CHAR(10) NOT NULL DEFAULT 'false',
  `enable_handling` CHAR(10) NOT NULL DEFAULT 'false',
  `pallet_enabled` VARCHAR(255) NULL DEFAULT 'false',
  `tares_enabled` VARCHAR(255) NULL DEFAULT 'false',
  `site_id` INT(10) UNSIGNED NOT NULL,
  `workstation_id` INT(10) UNSIGNED NOT NULL,
  `measure_type` CHAR(10) NOT NULL DEFAULT 'false',
  `deduct_flow` CHAR(10) NOT NULL DEFAULT 'default',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `settings_company_id_foreign` ON `settings` (`company_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_weighingheader_workstation_id` ON `settings` (`workstation_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_weighingheader_site_id` ON `settings` (`site_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sites` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sites` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_type` VARCHAR(255) NOT NULL,
  `site_name` VARCHAR(255) NOT NULL,
  `finger_active` VARCHAR(255) NULL DEFAULT NULL,
  `override_silo` VARCHAR(255) NULL DEFAULT NULL,
  `site_active` VARCHAR(255) NOT NULL,
  `custom_header_text` BLOB NOT NULL,
  `custom_footer_text` BLOB NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `measure_type` VARCHAR(225) NULL DEFAULT NULL,
  `deduct_flow` VARCHAR(225) NULL DEFAULT NULL,
  `decimals` INT(11) NULL DEFAULT 2,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tares` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tares` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `registration_no` VARCHAR(255) NOT NULL,
  `weight` DECIMAL(8,2) NOT NULL,
  `company_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `expiry_date` DATE NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `weighbridge_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transactions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `transactions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `current_id` INT(11) NOT NULL,
  `settings_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `company_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `contact_num` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `role_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `site_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `workstations_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `company_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `fingerprint` TEXT NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 104
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users_tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_tracking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users_tracking` (
  `id` INT(11) NOT NULL,
  `update_scope_id` VARCHAR(36) NULL DEFAULT NULL,
  `timestamp` BIGINT(20) NULL DEFAULT NULL,
  `sync_row_is_tombstone` BIT(1) NOT NULL DEFAULT b'0',
  `last_change_datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usertypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usertypes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usertypes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usertypes` VARCHAR(255) NOT NULL,
  `level` VARCHAR(255) NULL DEFAULT NULL,
  `companies` VARCHAR(255) NOT NULL,
  `sites` VARCHAR(255) NOT NULL,
  `workstations` VARCHAR(255) NOT NULL,
  `weighbridges` VARCHAR(255) NULL DEFAULT NULL,
  `cameras` VARCHAR(255) NOT NULL,
  `weigh_types` VARCHAR(255) NULL DEFAULT NULL,
  `weighing` VARCHAR(255) NOT NULL,
  `verify` VARCHAR(255) NOT NULL,
  `reprint` VARCHAR(255) NOT NULL,
  `business_partner` VARCHAR(255) NOT NULL,
  `products` VARCHAR(255) NOT NULL,
  `hauliers` VARCHAR(255) NOT NULL,
  `stored_tares` VARCHAR(255) NULL DEFAULT NULL,
  `rfid_vehicle` VARCHAR(255) NULL DEFAULT NULL,
  `axel_types` VARCHAR(255) NULL DEFAULT NULL,
  `axel_settings` VARCHAR(255) NULL DEFAULT NULL,
  `transaction_report` VARCHAR(255) NULL DEFAULT NULL,
  `exception_report` VARCHAR(255) NULL DEFAULT NULL,
  `users` VARCHAR(255) NULL DEFAULT NULL,
  `user_types` VARCHAR(255) NULL DEFAULT NULL,
  `delete_transaction_flag` VARCHAR(255) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usertypes_tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usertypes_tracking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usertypes_tracking` (
  `id` INT(11) NOT NULL,
  `update_scope_id` VARCHAR(36) NULL DEFAULT NULL,
  `timestamp` BIGINT(20) NULL DEFAULT NULL,
  `sync_row_is_tombstone` BIT(1) NOT NULL DEFAULT b'0',
  `last_change_datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `weighbridges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weighbridges` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `weighbridges` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `ip_address` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `port_num` VARCHAR(255) NOT NULL,
  `baud_rate` VARCHAR(255) NOT NULL,
  `data_bits` VARCHAR(255) NOT NULL,
  `parity` VARCHAR(255) NOT NULL,
  `stop_bits` VARCHAR(255) NOT NULL,
  `weight_reg` VARCHAR(255) NOT NULL,
  `weight_sep` VARCHAR(255) NULL DEFAULT NULL,
  `weight_num_amt` VARCHAR(255) NULL DEFAULT NULL,
  `weight_special` VARCHAR(255) NULL DEFAULT NULL,
  `decimal_places` VARCHAR(255) NOT NULL,
  `stable_samples` VARCHAR(255) NOT NULL,
  `manual` VARCHAR(255) NOT NULL,
  `in_reverse` VARCHAR(255) NOT NULL,
  `weight` DOUBLE(10,2) NOT NULL,
  `workstation_id` INT(10) UNSIGNED NOT NULL,
  `site_id` INT(10) UNSIGNED NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `weighing_transaction_flag` VARCHAR(255) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `scale` VARCHAR(255) NOT NULL,
  `remote_display` VARCHAR(255) NOT NULL,
  `display_ip_address` VARCHAR(255) NOT NULL,
  `display_port_num` VARCHAR(255) NOT NULL,
  `display_data_bits` VARCHAR(255) NOT NULL,
  `display_baud_rate` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `weighingcameras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weighingcameras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `weighingcameras` (
  `id` BINARY(16) NOT NULL,
  `base64` MEDIUMBLOB NULL DEFAULT NULL,
  `isnpr` VARCHAR(255) NOT NULL,
  `weighing_transaction_id` BINARY(16) NULL DEFAULT NULL,
  `site_id` INT(10) UNSIGNED NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `site_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `weighingheaders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weighingheaders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `weighingheaders` (
  `id` BINARY(16) NOT NULL,
  `transaction` VARCHAR(255) NULL DEFAULT NULL,
  `settings_id` INT(10) NULL DEFAULT NULL,
  `RegNumber` VARCHAR(255) NULL DEFAULT NULL,
  `RegNumber2` VARCHAR(255) NULL DEFAULT NULL,
  `RegNumber3` VARCHAR(255) NULL DEFAULT NULL,
  `Custom1` VARCHAR(255) NULL DEFAULT NULL,
  `Custom2` VARCHAR(255) NULL DEFAULT NULL,
  `Custom3` VARCHAR(255) NULL DEFAULT NULL,
  `Custom4` VARCHAR(255) NULL DEFAULT NULL,
  `Custom5` VARCHAR(255) NULL DEFAULT NULL,
  `Custom6` VARCHAR(255) NULL DEFAULT NULL,
  `Custom7` VARCHAR(255) NULL DEFAULT NULL,
  `Custom8` VARCHAR(255) NULL DEFAULT NULL,
  `Custom9` VARCHAR(255) NULL DEFAULT NULL,
  `Custom10` VARCHAR(255) NULL DEFAULT NULL,
  `FirstWeight` DOUBLE(18,4) NULL DEFAULT NULL,
  `SecondWeight` DOUBLE(18,4) NULL DEFAULT NULL,
  `TotalWeight` DOUBLE(18,4) NULL DEFAULT NULL,
  `NettWeight` INT(11) NULL DEFAULT NULL,
  `businesspartner_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `product_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `grade_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `haulier_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `weighbridge_id` INT(10) UNSIGNED NOT NULL,
  `site_id` INT(10) UNSIGNED NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `Custom11` VARCHAR(255) NULL DEFAULT NULL,
  `Custom12` VARCHAR(255) NULL DEFAULT NULL,
  `Custom13` VARCHAR(255) NULL DEFAULT NULL,
  `Custom14` VARCHAR(255) NULL DEFAULT NULL,
  `Custom15` VARCHAR(255) NULL DEFAULT NULL,
  `Custom16` VARCHAR(255) NULL DEFAULT NULL,
  `Custom17` VARCHAR(255) NULL DEFAULT NULL,
  `Custom18` VARCHAR(255) NULL DEFAULT NULL,
  `Custom19` VARCHAR(255) NULL DEFAULT NULL,
  `Custom20` VARCHAR(255) NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `price` DECIMAL(8,2) NULL DEFAULT 0.00,
  `moisture_deduction` DECIMAL(8,2) NULL DEFAULT 0.00,
  `handling_charges` DECIMAL(11,2) NULL DEFAULT 0.00,
  `pallet_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `pallet_charges` DECIMAL(8,2) NULL DEFAULT 0.00,
  `pallet_count` INT(11) NULL DEFAULT 0,
  `tare_id` INT(11) NULL DEFAULT NULL,
  `firstWeightUserId` INT(10) UNSIGNED NOT NULL DEFAULT 21,
  `secondWeightUserId` INT(10) UNSIGNED NULL DEFAULT NULL,
  `verifyUserId` INT(10) UNSIGNED NULL DEFAULT NULL,
  `deletedUserId` INT(10) UNSIGNED NULL DEFAULT NULL,
  `workstation_id` INT(10) UNSIGNED NOT NULL,
  `moisture_threshold` DECIMAL(8,2) NULL DEFAULT NULL,
  `moistureCoefficient` DECIMAL(20,8) NULL DEFAULT NULL,
  `moistureWeight` DECIMAL(20,8) NULL DEFAULT NULL,
  `handlingWeight` DECIMAL(20,8) NULL DEFAULT NULL,
  `grades` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `INDX_weighingheaders_select` ON `weighingheaders` (`deleted_at` ASC, `company_id` ASC, `site_id` ASC, `workstation_id` ASC, `status` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `weighingtransactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weighingtransactions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `weighingtransactions` (
  `id` BINARY(16) NOT NULL,
  `Status` VARCHAR(255) NOT NULL,
  `Weight1` DECIMAL(15,2) NOT NULL,
  `Weight2` DECIMAL(15,2) NOT NULL,
  `Weight3` DECIMAL(15,2) NOT NULL,
  `Weight4` DECIMAL(15,2) NOT NULL,
  `Weight5` DECIMAL(15,2) NOT NULL,
  `Weight6` DECIMAL(15,2) NOT NULL,
  `WeightTotal` DECIMAL(15,2) NOT NULL,
  `weighing_header_id` BINARY(16) NULL DEFAULT NULL,
  `site_id` INT(10) UNSIGNED NOT NULL,
  `workstation_id` INT(10) NULL DEFAULT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `AxelSetups` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workstations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workstations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workstations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `workstation_type` VARCHAR(255) NOT NULL,
  `workstation_name` VARCHAR(255) NOT NULL,
  `workstation_active` VARCHAR(255) NOT NULL,
  `site_id` INT(10) UNSIGNED NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
USE `weighsoft` ;

-- -----------------------------------------------------
-- function BIN_TO_UUID
-- -----------------------------------------------------

USE `weighsoft`;
DROP function IF EXISTS `BIN_TO_UUID`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`weighsoft`@`%` FUNCTION `BIN_TO_UUID`(b BINARY(16), f BOOLEAN) RETURNS char(36) CHARSET utf8
    DETERMINISTIC
BEGIN
   DECLARE hexStr CHAR(32);
   SET hexStr = HEX(b);
   RETURN LOWER(CONCAT(
        IF(f,SUBSTR(hexStr, 9, 8),SUBSTR(hexStr, 1, 8)), '-',
        IF(f,SUBSTR(hexStr, 5, 4),SUBSTR(hexStr, 9, 4)), '-',
        IF(f,SUBSTR(hexStr, 1, 4),SUBSTR(hexStr, 13, 4)), '-',
        SUBSTR(hexStr, 17, 4), '-',
        SUBSTR(hexStr, 21)
    ));
END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- function UUID_TO_BIN
-- -----------------------------------------------------

USE `weighsoft`;
DROP function IF EXISTS `UUID_TO_BIN`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`weighsoft`@`%` FUNCTION `UUID_TO_BIN`(uuid CHAR(36), f BOOLEAN) RETURNS binary(16)
    DETERMINISTIC
BEGIN
  RETURN UNHEX(CONCAT(
  IF(f,SUBSTRING(uuid, 15, 4),SUBSTRING(uuid, 1, 8)),
  SUBSTRING(uuid, 10, 4),
  IF(f,SUBSTRING(uuid, 1, 8),SUBSTRING(uuid, 15, 4)),
  SUBSTRING(uuid, 20, 4),
  SUBSTRING(uuid, 25))
  );
END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure users_Weighsoft_changes
-- -----------------------------------------------------

USE `weighsoft`;
DROP procedure IF EXISTS `users_Weighsoft_changes`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`root`@`%` PROCEDURE `users_Weighsoft_changes`(

	`sync_min_timestamp` bigint  ,
	`sync_scope_id` char (36)  
)
BEGIN
SELECT DISTINCT	`side`.`id`, 
	`base`.`firstname`, 
	`base`.`lastname`, 
	`base`.`contact_num`, 
	`base`.`email`, 
	`base`.`password`, 
	`base`.`role_id`, 
	`base`.`site_id`, 
	`base`.`workstations_id`, 
	`base`.`company_id`, 
	`base`.`token`, 
	`base`.`updated_at`, 
	`base`.`created_at`, 
	`base`.`fingerprint`, 
	`base`.`deleted_at`, 
	`side`.`sync_row_is_tombstone`, 
	`side`.`update_scope_id` as `sync_update_scope_id` 
FROM `users` `base`
RIGHT JOIN `users_tracking` `side` ON `base`.`id` = `side`.`id`
WHERE (
	`side`.`timestamp` > sync_min_timestamp
	AND (`side`.`update_scope_id` <> sync_scope_id OR `side`.`update_scope_id` IS NULL) 
);

END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure users_Weighsoft_delete
-- -----------------------------------------------------

USE `weighsoft`;
DROP procedure IF EXISTS `users_Weighsoft_delete`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`root`@`%` PROCEDURE `users_Weighsoft_delete`(

	`in_id` int(10) unsigned  ,
	`sync_scope_id` char (36)  ,
	`sync_force_write` int  ,
	`sync_min_timestamp` bigint  ,
	OUT `sync_row_count` int  
)
BEGIN

DECLARE ts BIGINT;
DECLARE t_update_scope_id VARCHAR(36);
SET ts = 0;
SELECT `timestamp`, `update_scope_id` FROM `users_tracking` WHERE `users_tracking`.`id` = `in_id` LIMIT 1 INTO ts, t_update_scope_id;
DELETE FROM `users` WHERE
`id` = `in_id`
AND (ts <= sync_min_timestamp OR ts IS NULL OR t_update_scope_id = sync_scope_id OR sync_force_write = 1);

SELECT ROW_COUNT() INTO sync_row_count;


IF (sync_row_count > 0) THEN
	UPDATE `users_tracking`
	SET `update_scope_id` = sync_scope_id, 
		 `sync_row_is_tombstone` = 1, 
		 `timestamp` = ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(6)) * 10000), 
		 `last_change_datetime` = now() 
	WHERE `id` = `in_id`;
END IF;

END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure users_Weighsoft_deletemetadata
-- -----------------------------------------------------

USE `weighsoft`;
DROP procedure IF EXISTS `users_Weighsoft_deletemetadata`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`root`@`%` PROCEDURE `users_Weighsoft_deletemetadata`(

	`sync_row_timestamp` bigint  
)
BEGIN

DELETE FROM `users_tracking` WHERE `timestamp` < sync_row_timestamp;

END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure users_Weighsoft_initialize
-- -----------------------------------------------------

USE `weighsoft`;
DROP procedure IF EXISTS `users_Weighsoft_initialize`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`root`@`%` PROCEDURE `users_Weighsoft_initialize`(

	`sync_min_timestamp` bigint  
)
BEGIN
SELECT
	`base`.`id`
, 	`base`.`firstname`
, 	`base`.`lastname`
, 	`base`.`contact_num`
, 	`base`.`email`
, 	`base`.`password`
, 	`base`.`role_id`
, 	`base`.`site_id`
, 	`base`.`workstations_id`
, 	`base`.`company_id`
, 	`base`.`token`
, 	`base`.`updated_at`
, 	`base`.`created_at`
, 	`base`.`fingerprint`
, 	`base`.`deleted_at`
FROM `users` `base`
LEFT JOIN `users_tracking` `side` ON `base`.`id` = `side`.`id`
WHERE (
	(`side`.`timestamp` > sync_min_timestamp or sync_min_timestamp IS NULL));

END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure users_Weighsoft_reset
-- -----------------------------------------------------

USE `weighsoft`;
DROP procedure IF EXISTS `users_Weighsoft_reset`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`root`@`%` PROCEDURE `users_Weighsoft_reset`(

)
BEGIN
DELETE FROM `users`;
DELETE FROM `users_tracking`;


END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure users_Weighsoft_selectrow
-- -----------------------------------------------------

USE `weighsoft`;
DROP procedure IF EXISTS `users_Weighsoft_selectrow`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`root`@`%` PROCEDURE `users_Weighsoft_selectrow`(

	`in_id` int(10) unsigned  ,
	`sync_scope_id` char (36)  
)
BEGIN
SELECT 
	`side`.`id`, 
	`base`.`firstname`, 
	`base`.`lastname`, 
	`base`.`contact_num`, 
	`base`.`email`, 
	`base`.`password`, 
	`base`.`role_id`, 
	`base`.`site_id`, 
	`base`.`workstations_id`, 
	`base`.`company_id`, 
	`base`.`token`, 
	`base`.`updated_at`, 
	`base`.`created_at`, 
	`base`.`fingerprint`, 
	`base`.`deleted_at`, 
	`side`.`sync_row_is_tombstone`, 
	`side`.`update_scope_id` as `sync_update_scope_id`
FROM `users` `base`
RIGHT JOIN `users_tracking` `side` ON
`base`.`id` = `side`.`id`
WHERE `side`.`id` = in_id;
END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure users_Weighsoft_update
-- -----------------------------------------------------

USE `weighsoft`;
DROP procedure IF EXISTS `users_Weighsoft_update`;
SHOW WARNINGS;

DELIMITER $$
USE `weighsoft`$$
CREATE DEFINER=`root`@`%` PROCEDURE `users_Weighsoft_update`(

	`in_id` int(10) unsigned  ,
	`in_firstname` varchar(255)  ,
	`in_lastname` varchar(255)  ,
	`in_contact_num` varchar(255)  ,
	`in_email` varchar(255)  ,
	`in_password` varchar(60)  ,
	`in_role_id` int(10) unsigned  ,
	`in_site_id` int(10) unsigned  ,
	`in_workstations_id` int(10) unsigned  ,
	`in_company_id` int(10) unsigned  ,
	`in_token` varchar(255)  ,
	`in_updated_at` datetime  ,
	`in_created_at` datetime  ,
	`in_fingerprint` text  ,
	`in_deleted_at` datetime  ,
	`sync_scope_id` char (36)  ,
	`sync_force_write` int  ,
	`sync_min_timestamp` bigint  ,
	OUT `sync_row_count` int  
)
BEGIN
DECLARE `t_in_id` int(10) unsigned  ;
DECLARE ts BIGINT;
DECLARE t_update_scope_id VARCHAR(36);
SET ts = 0;
SELECT `id`, 
`timestamp`, `update_scope_id` FROM `users_tracking` 
WHERE `users_tracking`.`id` = `in_id` LIMIT 1 
INTO `t_in_id`,  ts, t_update_scope_id;

UPDATE `users`
SET  `firstname` = `in_firstname`
,  `lastname` = `in_lastname`
,  `contact_num` = `in_contact_num`
,  `email` = `in_email`
,  `password` = `in_password`
,  `role_id` = `in_role_id`
,  `site_id` = `in_site_id`
,  `workstations_id` = `in_workstations_id`
,  `company_id` = `in_company_id`
,  `token` = `in_token`
,  `updated_at` = `in_updated_at`
,  `created_at` = `in_created_at`
,  `fingerprint` = `in_fingerprint`
,  `deleted_at` = `in_deleted_at`
WHERE `id` = `in_id` AND (ts <= sync_min_timestamp OR ts IS NULL OR t_update_scope_id  = sync_scope_id OR sync_force_write = 1);

SELECT ROW_COUNT() INTO sync_row_count;
IF (sync_row_count = 0) THEN
	INSERT  INTO `users`
	(`id`, `firstname`, `lastname`, `contact_num`, `email`, `password`, `role_id`, `site_id`, `workstations_id`, `company_id`, `token`, `updated_at`, `created_at`, `fingerprint`, `deleted_at`)
	SELECT * FROM ( SELECT `in_id`, `in_firstname`, `in_lastname`, `in_contact_num`, `in_email`, `in_password`, `in_role_id`, `in_site_id`, `in_workstations_id`, `in_company_id`, `in_token`, `in_updated_at`, `in_created_at`, `in_fingerprint`, `in_deleted_at`) as TMP 
	WHERE ( `t_in_id` IS NULL )
	OR (ts <= sync_min_timestamp OR ts IS NULL OR t_update_scope_id = sync_scope_id OR sync_force_write = 1)
	LIMIT 1;

SELECT ROW_COUNT() INTO sync_row_count;

END IF;

IF (sync_row_count > 0) THEN
	UPDATE `users_tracking`
	SET `update_scope_id` = sync_scope_id, 
		 `sync_row_is_tombstone` = 0, 
		 `timestamp` = ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(6)) * 10000), 
		 `last_change_datetime` = now() 
	WHERE `id` = `in_id`;
END IF;

END$$

DELIMITER ;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
