CREATE TABLE `axelsetups` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `steering` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `steering_max` int(11) NOT NULL DEFAULT 0,
  `axel_1` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `axel_1_max` int(11) NOT NULL DEFAULT 0,
  `axel_2` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `axel_2_max` int(11) NOT NULL DEFAULT 0,
  `axel_3` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `axel_3_max` int(11) NOT NULL DEFAULT 0,
  `axel_4` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `axel_4_max` int(11) NOT NULL DEFAULT 0,
  `vehicle_max` int(11) NOT NULL DEFAULT 0,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `axelsetups_company_id_foreign` (`company_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `axletypes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Single_Steering` int(11) NOT NULL DEFAULT 0,
  `Double_Steering` int(11) NOT NULL DEFAULT 0,
  `Triple_Steering` int(11) NOT NULL DEFAULT 0,
  `Single_Non_Steering` int(11) NOT NULL DEFAULT 0,
  `Double_Non_Steering` int(11) NOT NULL DEFAULT 0,
  `Triple_Non_Steering` int(11) NOT NULL DEFAULT 0,
  `Double_Single_Non_Steering` int(11) NOT NULL,
  `Double_Double_Non_Steering` int(11) NOT NULL,
  `Double_Triple_Non_Steering` int(11) NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `Custom_1` int(11) NOT NULL DEFAULT 0,
  `Custom_2` int(11) NOT NULL DEFAULT 0,
  `Custom_3` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `axletypes_company_id_foreign` (`company_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `businesspartners` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `site_id` int(10) NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `vat_nr` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `street` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `suburb` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `postal_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `businesspartners_company_id_foreign` (`company_id`),
  CONSTRAINT `businesspartners_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=687 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `cameras` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `pn_recog` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ip_address` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `camera_active` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `weighbridge_id` int(10) unsigned NOT NULL,
  `workstation_id` int(10) unsigned NOT NULL,
  `site_id` int(10) unsigned NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `auth_type` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `username` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `password` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cameras_weighbridge_id_foreign` (`weighbridge_id`),
  KEY `cameras_workstation_id_foreign` (`workstation_id`),
  KEY `cameras_site_id_foreign` (`site_id`),
  KEY `cameras_company_id_foreign` (`company_id`),
  CONSTRAINT `cameras_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `cameras_site_id_foreign` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`),
  CONSTRAINT `cameras_weighbridge_id_foreign` FOREIGN KEY (`weighbridge_id`) REFERENCES `weighbridges` (`id`),
  CONSTRAINT `cameras_workstation_id_foreign` FOREIGN KEY (`workstation_id`) REFERENCES `workstations` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `companies` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `registered_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `tel` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `fax` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `registration_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `vat_nr` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `contact_person` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `cell` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `suburb1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `city1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `postal_code1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `po_box` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `suburb2` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `city2` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `postal_code2` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `delete_transaction_flag` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `terms` varchar(4000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `display_custom_logo_img` blob DEFAULT NULL,
  `smart_hauliers` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `contract_transactions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `contract_id` int(11) NOT NULL,
  `amount` double(11,2) NOT NULL,
  `weighing_header_id` binary(16) DEFAULT NULL,
  `site_id` int(11) NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `company_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_weighing_header_id` (`weighing_header_id`),
  CONSTRAINT `FK_weighing_header_id` FOREIGN KEY (`weighing_header_id`) REFERENCES `weighingheaders` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2025 DEFAULT CHARSET=latin1;

CREATE TABLE `contracts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `businesspartner_id` int(11) NOT NULL,
  `expiry_date` datetime NOT NULL,
  `direction` varchar(255) NOT NULL,
  `price` decimal(10,4) DEFAULT NULL,
  `amount` varchar(255) NOT NULL,
  `product_id` int(11) NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `company_id` int(11) NOT NULL,
  `site_id` int(11) NOT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `linked_contact_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=165 DEFAULT CHARSET=latin1;

CREATE TABLE `errorlog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(255) COLLATE utf8_bin NOT NULL,
  `description` varchar(2000) COLLATE utf8_bin NOT NULL,
  `jsondata` varchar(2000) COLLATE utf8_bin NOT NULL,
  `comment` varchar(255) COLLATE utf8_bin NOT NULL,
  `weighbridge_id` int(11) NOT NULL,
  `workstation_id` int(11) NOT NULL,
  `site_id` int(11) NOT NULL,
  `company_id` int(11) NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `exceptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(255) COLLATE utf8_bin NOT NULL,
  `description` varchar(2000) COLLATE utf8_bin NOT NULL,
  `jsondata` varchar(2000) COLLATE utf8_bin NOT NULL,
  `comment` varchar(255) COLLATE utf8_bin NOT NULL,
  `weighbridge_id` int(11) NOT NULL,
  `workstation_id` int(11) NOT NULL,
  `site_id` int(11) NOT NULL,
  `company_id` int(11) NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=176 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `grades` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `grades_company_id_foreign` (`company_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `hauliers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `site_id` int(10) NOT NULL,
  `business_partner_id` int(10) unsigned DEFAULT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`,`site_id`),
  KEY `hauliers_company_id_foreign` (`company_id`),
  KEY `idx_hauliers_business_partner` (`business_partner_id`),
  CONSTRAINT `fk_hauliers_business_partner` FOREIGN KEY (`business_partner_id`) REFERENCES `businesspartners` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hauliers_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=335 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `migrations` (
  `migration` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `pallets` (
  `pallet_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pallet_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `amount` decimal(8,2) NOT NULL,
  `company_id` int(11) NOT NULL,
  `site_id` int(11) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`pallet_id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `vat` decimal(11,2) DEFAULT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `purchase_price` decimal(10,2) DEFAULT NULL,
  `sale_price` decimal(10,2) DEFAULT NULL,
  `grades_enabled` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'No',
  `grades` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `products_company_id_foreign` (`company_id`),
  CONSTRAINT `products_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=234 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `reporting` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `jsondata` varchar(4000) DEFAULT NULL,
  `company_id` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) DEFAULT NULL,
  `created_at` varchar(255) DEFAULT NULL,
  `deleted_at` varchar(255) DEFAULT NULL,
  `show_deleted` varchar(255) NOT NULL DEFAULT 'No',
  `email` varchar(255) DEFAULT NULL,
  `schedule` varchar(20) DEFAULT NULL,
  `last_report_on` datetime DEFAULT NULL,
  `time_frame` int(11) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE `rfid_vehicles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `registration_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `rfid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `haulier_id` int(10) unsigned DEFAULT NULL,
  `site_id` int(10) unsigned DEFAULT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `rfid_vehicles_company_id_foreign` (`company_id`),
  KEY `idx_rfid_vehicles_haulier` (`haulier_id`),
  KEY `idx_rfid_vehicles_site` (`site_id`),
  CONSTRAINT `rfid_vehicles_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `rfid_vehicles_haulier_id_foreign` FOREIGN KEY (`haulier_id`) REFERENCES `hauliers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `rfid_vehicles_site_id_foreign` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `scope_info` (
  `sync_scope_id` varchar(36) NOT NULL,
  `sync_scope_name` varchar(100) NOT NULL,
  `sync_scope_schema` longtext DEFAULT NULL,
  `sync_scope_setup` longtext DEFAULT NULL,
  `sync_scope_version` varchar(10) DEFAULT NULL,
  `scope_last_sync` datetime DEFAULT NULL,
  `scope_last_server_sync_timestamp` bigint(20) DEFAULT NULL,
  `scope_last_sync_timestamp` bigint(20) DEFAULT NULL,
  `scope_last_sync_duration` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`sync_scope_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `haulier` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `stored_tares` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `numberplate_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `numberplate_recognition` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `numberplate_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `numberplate_3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `business_partner` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `use_product_list` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type_of_weighing` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0.00',
  `first_can_axel` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `second_can_axel` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0.00',
  `goods_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `print_ticket` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `reprint` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'text',
  `custom_fields` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input1` text COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_name1` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val1` blob DEFAULT NULL,
  `user_defined_rep1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input2` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `user_defined_name2` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val2` blob NOT NULL,
  `user_defined_rep2` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input3` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `user_defined_name3` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val3` blob NOT NULL,
  `user_defined_rep3` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input4` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `user_defined_name4` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val4` blob NOT NULL,
  `user_defined_rep4` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input5` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `user_defined_name5` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val5` blob NOT NULL,
  `user_defined_rep5` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input6` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `user_defined_name6` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val6` blob NOT NULL,
  `user_defined_rep6` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input7` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `user_defined_name7` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val7` blob NOT NULL,
  `user_defined_rep7` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input8` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `user_defined_name8` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val8` blob NOT NULL,
  `user_defined_rep8` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input9` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `user_defined_name9` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  `user_defined_val9` blob NOT NULL,
  `user_defined_rep9` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_defined_input10` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name10` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val10` blob NOT NULL,
  `user_defined_rep10` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `AS_400_path` text COLLATE utf8_unicode_ci NOT NULL,
  `export_AS400` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `silo_verification` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `use_cameras` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `display_cameras` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `print_cameras_on_ticket` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ticket_header` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `display_custom_header_img` blob DEFAULT NULL,
  `ticket_footer` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `display_custom_footer_img` blob DEFAULT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `user_defined_input11` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name11` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val11` blob DEFAULT NULL,
  `user_defined_rep11` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input12` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name12` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val12` blob DEFAULT NULL,
  `user_defined_rep12` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input13` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name13` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val13` blob DEFAULT NULL,
  `user_defined_rep13` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input14` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name14` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val14` blob DEFAULT NULL,
  `user_defined_rep14` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input15` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name15` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val15` blob DEFAULT NULL,
  `user_defined_rep15` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input16` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name16` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val16` blob DEFAULT NULL,
  `user_defined_rep16` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input17` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name17` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val17` blob DEFAULT NULL,
  `user_defined_rep17` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input18` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name18` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val18` blob DEFAULT NULL,
  `user_defined_rep18` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input19` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name19` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val19` blob DEFAULT NULL,
  `user_defined_rep19` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_input20` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_name20` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_defined_val20` blob DEFAULT NULL,
  `user_defined_rep20` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `2nd_weighing` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `invoice_enabled` varchar(25) COLLATE utf8_unicode_ci DEFAULT 'false',
  `contract_enabled` varchar(25) COLLATE utf8_unicode_ci DEFAULT 'false',
  `moisture_deduction_level` decimal(8,2) DEFAULT 0.00,
  `prefix` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `enable_moisture` char(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `enable_handling` char(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'false',
  `pallet_enabled` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `tares_enabled` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'false',
  `site_id` int(10) unsigned NOT NULL,
  `workstation_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `settings_company_id_foreign` (`company_id`),
  KEY `FK_weighingheader_workstation_id` (`workstation_id`),
  KEY `FK_weighingheader_site_id` (`site_id`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `sites` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `site_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `site_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `finger_active` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `override_silo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `site_active` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `custom_header_text` blob NOT NULL,
  `custom_footer_text` blob NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `measure_type` char(10) COLLATE utf8_unicode_ci DEFAULT 'KG',
  `deduct_flow` char(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `decimals` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sites_company_id_foreign` (`company_id`),
  CONSTRAINT `sites_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `tares` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `registration_no` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `weight` decimal(8,2) NOT NULL,
  `company_id` int(11) NOT NULL,
  `site_id` int(11) NOT NULL,
  `expiry_date` date NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `weighbridge_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `current_id` int(11) NOT NULL,
  `settings_id` int(11) NOT NULL,
  `site_id` int(11) NOT NULL,
  `company_id` int(11) NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `firstname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `contact_num` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `role_id` int(10) unsigned DEFAULT NULL,
  `site_id` int(10) unsigned DEFAULT NULL,
  `workstations_id` int(10) unsigned DEFAULT NULL,
  `company_id` int(10) unsigned DEFAULT NULL,
  `token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `fingerprint` text COLLATE utf8_unicode_ci NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_role_id_foreign` (`role_id`),
  KEY `users_company_id_foreign` (`company_id`),
  KEY `users_site_id_foreign` (`site_id`),
  KEY `users_workstations_id_foreign` (`workstations_id`),
  CONSTRAINT `users_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `users_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `usertypes` (`id`),
  CONSTRAINT `users_site_id_foreign` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`),
  CONSTRAINT `users_workstations_id_foreign` FOREIGN KEY (`workstations_id`) REFERENCES `workstations` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=109 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `usertypes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `usertypes` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `level` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `companies` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `sites` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `workstations` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `weighbridges` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cameras` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `weigh_types` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `weighing` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `verify` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `reprint` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `business_partner` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `products` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `hauliers` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `stored_tares` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rfid_vehicle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `axel_types` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `axel_settings` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `transaction_report` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `exception_report` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `users` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_types` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `delete_transaction_flag` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `weighbridges` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ip_address` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `port_num` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `scale` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `remote_display` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `baud_rate` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `data_bits` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `parity` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `stop_bits` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `weight_reg` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `weight_sep` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `weight_num_amt` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `weight_special` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `decimal_places` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `stable_samples` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `manual` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `in_reverse` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `weight` double(10,2) NOT NULL,
  `workstation_id` int(10) unsigned NOT NULL,
  `site_id` int(10) unsigned NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `weighing_transaction_flag` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `display_ip_address` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `display_port_num` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `display_baud_rate` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `display_data_bits` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Display_stop_bits` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `weighbridges_workstation_id_foreign` (`workstation_id`),
  KEY `weighbridges_site_id_foreign` (`site_id`),
  KEY `weighbridges_company_id_foreign` (`company_id`),
  CONSTRAINT `weighbridges_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `weighbridges_site_id_foreign` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`),
  CONSTRAINT `weighbridges_workstation_id_foreign` FOREIGN KEY (`workstation_id`) REFERENCES `workstations` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `weighingcameras` (
  `id` binary(16) NOT NULL,
  `base64` mediumblob DEFAULT NULL,
  `isnpr` varchar(255) NOT NULL,
  `weighing_transaction_id` binary(16) DEFAULT NULL,
  `site_id` int(10) unsigned NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`,`site_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `weighingheaders` (
  `id` binary(16) NOT NULL,
  `transaction` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `settings_id` int(10) DEFAULT NULL,
  `RegNumber` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `RegNumber2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `RegNumber3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom4` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom5` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom6` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom7` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom8` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom9` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom10` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `FirstWeight` double(18,4) DEFAULT NULL,
  `SecondWeight` double(18,4) DEFAULT NULL,
  `TotalWeight` double(18,4) DEFAULT NULL,
  `NettWeight` double(18,4) DEFAULT NULL,
  `businesspartner_id` int(10) unsigned DEFAULT NULL,
  `product_id` int(10) unsigned DEFAULT NULL,
  `grade_id` int(10) unsigned DEFAULT NULL,
  `grades` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `haulier_id` int(10) unsigned DEFAULT NULL,
  `weighbridge_id` int(10) unsigned NOT NULL,
  `site_id` int(10) unsigned NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `Custom11` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom12` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom13` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom14` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom15` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom16` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom17` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom18` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom19` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Custom20` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `reason` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `price` decimal(8,2) DEFAULT 0.00,
  `moisture_deduction` decimal(8,2) DEFAULT 0.00,
  `handling_charges` decimal(11,2) DEFAULT 0.00,
  `pallet_id` int(10) unsigned DEFAULT NULL,
  `pallet_charges` decimal(8,2) DEFAULT 0.00,
  `pallet_count` int(11) DEFAULT 0,
  `tare_id` int(11) DEFAULT NULL,
  `firstWeightUserId` int(10) unsigned NOT NULL DEFAULT 21,
  `secondWeightUserId` int(10) unsigned DEFAULT NULL,
  `verifyUserId` int(10) unsigned DEFAULT NULL,
  `deletedUserId` int(10) unsigned DEFAULT NULL,
  `workstation_id` int(10) unsigned NOT NULL,
  `moisture_threshold` decimal(8,2) DEFAULT NULL,
  `moistureCoefficient` decimal(20,8) DEFAULT NULL,
  `moistureWeight` decimal(20,8) DEFAULT NULL,
  `handlingWeight` decimal(20,8) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `weighingheaders_businesspartner_id_foreign` (`businesspartner_id`),
  KEY `weighingheaders_product_id_foreign` (`product_id`),
  KEY `weighingheaders_grade_id_foreign` (`grade_id`),
  KEY `weighingheaders_haulier_id_foreign` (`haulier_id`),
  KEY `weighingheaders_weighbridge_id_foreign` (`weighbridge_id`),
  KEY `weighingheaders_site_id_foreign` (`site_id`),
  KEY `weighingheaders_company_id_foreign` (`company_id`),
  KEY `weighingheaders_pallet_id_foreign` (`pallet_id`),
  KEY `FK_FirstWeightUserWeighingheader` (`firstWeightUserId`),
  KEY `FK_SecondWeightUserWeighingheader` (`secondWeightUserId`),
  KEY `FK_VerifyUserWeighingheader` (`verifyUserId`),
  KEY `FK_DeletedUserWeighingheader` (`deletedUserId`),
  KEY `FK_weighingheaders_workstation_id` (`workstation_id`),
  KEY `INDX_weighingheaders_select` (`deleted_at`,`company_id`,`site_id`,`workstation_id`,`status`),
  CONSTRAINT `FK_DeletedUserWeighingheader` FOREIGN KEY (`deletedUserId`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_FirstWeightUserWeighingheader` FOREIGN KEY (`firstWeightUserId`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_SecondWeightUserWeighingheader` FOREIGN KEY (`secondWeightUserId`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_VerifyUserWeighingheader` FOREIGN KEY (`verifyUserId`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_weighingheaders_workstation_id` FOREIGN KEY (`workstation_id`) REFERENCES `workstations` (`id`),
  CONSTRAINT `weighingheaders_businesspartner_id_foreign` FOREIGN KEY (`businesspartner_id`) REFERENCES `businesspartners` (`id`),
  CONSTRAINT `weighingheaders_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `weighingheaders_grade_id_foreign` FOREIGN KEY (`grade_id`) REFERENCES `grades` (`id`),
  CONSTRAINT `weighingheaders_haulier_id_foreign` FOREIGN KEY (`haulier_id`) REFERENCES `hauliers` (`id`),
  CONSTRAINT `weighingheaders_pallet_id_foreign` FOREIGN KEY (`pallet_id`) REFERENCES `pallets` (`pallet_id`),
  CONSTRAINT `weighingheaders_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `weighingheaders_site_id_foreign` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`),
  CONSTRAINT `weighingheaders_weighbridge_id_foreign` FOREIGN KEY (`weighbridge_id`) REFERENCES `weighbridges` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `weighingtransactions` (
  `id` binary(16) NOT NULL,
  `Status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Weight1` decimal(15,2) NOT NULL,
  `Weight2` decimal(15,2) NOT NULL,
  `Weight3` decimal(15,2) NOT NULL,
  `Weight4` decimal(15,2) NOT NULL,
  `Weight5` decimal(15,2) NOT NULL,
  `Weight6` decimal(15,2) NOT NULL,
  `WeightTotal` decimal(15,2) NOT NULL,
  `weighing_header_id` binary(16) DEFAULT NULL,
  `site_id` int(10) unsigned NOT NULL,
  `workstation_id` int(10) DEFAULT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `AxelSetups` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `weighingtransactions_site_id_foreign` (`site_id`),
  KEY `weighingtransactions_company_id_foreign` (`company_id`),
  KEY `weighingtransactions_weighing_header_id_foreign` (`weighing_header_id`),
  CONSTRAINT `weighingtransactions_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `weighingtransactions_site_id_foreign` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`),
  CONSTRAINT `weighingtransactions_weighing_header_id_foreign` FOREIGN KEY (`weighing_header_id`) REFERENCES `weighingheaders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `workstations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `workstation_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `workstation_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `workstation_active` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `incoming_boom_ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `exiting_boom_ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `incoming_light_ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `exiting_light_ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `site_id` int(10) unsigned NOT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `incoming_boom_relay` tinyint(4) DEFAULT NULL COMMENT 'ESP32 relay number (1-8) for incoming boom',
  `exiting_boom_relay` tinyint(4) DEFAULT NULL COMMENT 'ESP32 relay number (1-8) for exiting boom',
  `incoming_light_relay` tinyint(4) DEFAULT NULL COMMENT 'ESP32 relay number (1-8) for incoming light',
  `exiting_light_relay` tinyint(4) DEFAULT NULL COMMENT 'ESP32 relay number (1-8) for exiting light',
  PRIMARY KEY (`id`),
  KEY `workstations_site_id_foreign` (`site_id`),
  KEY `workstations_company_id_foreign` (`company_id`),
  CONSTRAINT `workstations_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `workstations_site_id_foreign` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `rfid_vehicles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `registration_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `rfid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `haulier_id` int(10) unsigned DEFAULT NULL,
  `site_id` int(10) unsigned DEFAULT NULL,
  `company_id` int(10) unsigned NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `rfid_vehicles_company_id_foreign` (`company_id`),
  KEY `idx_rfid_vehicles_haulier` (`haulier_id`),
  KEY `idx_rfid_vehicles_site` (`site_id`),
  CONSTRAINT `rfid_vehicles_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `rfid_vehicles_haulier_id_foreign` FOREIGN KEY (`haulier_id`) REFERENCES `hauliers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `rfid_vehicles_site_id_foreign` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
